//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procajas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Procajas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string acceptText {
            get {
                return ResourceManager.GetString("acceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelText {
            get {
                return ResourceManager.GetString("cancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumidos.
        /// </summary>
        public static string consumedText {
            get {
                return ResourceManager.GetString("consumedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registro(s) fueron creados..
        /// </summary>
        public static string createNotificationText {
            get {
                return ResourceManager.GetString("createNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string createText {
            get {
                return ResourceManager.GetString("createText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string dateText {
            get {
                return ResourceManager.GetString("dateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registro(s) fueron borrados..
        /// </summary>
        public static string deleteNotificationText {
            get {
                return ResourceManager.GetString("deleteNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string deleteText {
            get {
                return ResourceManager.GetString("deleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación destino.
        /// </summary>
        public static string destinationLocationText {
            get {
                return ResourceManager.GetString("destinationLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existentes.
        /// </summary>
        public static string existingText {
            get {
                return ResourceManager.GetString("existingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de producto terminado.
        /// </summary>
        public static string finishedProductLocationText {
            get {
                return ResourceManager.GetString("finishedProductLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada.
        /// </summary>
        public static string inputText {
            get {
                return ResourceManager.GetString("inputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada a Almacén.
        /// </summary>
        public static string inputToWarehouseText {
            get {
                return ResourceManager.GetString("inputToWarehouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string invoiceText {
            get {
                return ResourceManager.GetString("invoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es válido.
        /// </summary>
        public static string isValidText {
            get {
                return ResourceManager.GetString("isValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string itemNameText {
            get {
                return ResourceManager.GetString("itemNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string locationText {
            get {
                return ResourceManager.GetString("locationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material de entrada.
        /// </summary>
        public static string materialInputText {
            get {
                return ResourceManager.GetString("materialInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material de salida.
        /// </summary>
        public static string materialOutputText {
            get {
                return ResourceManager.GetString("materialOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las primeras 3 letras del nombre del material deben ser las 3 letras del proceso en mayúscula..
        /// </summary>
        public static string materialProcessMismatchText {
            get {
                return ResourceManager.GetString("materialProcessMismatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales en este proceso.
        /// </summary>
        public static string materialsInThisProcessText {
            get {
                return ResourceManager.GetString("materialsInThisProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string materialText {
            get {
                return ResourceManager.GetString("materialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material a usar.
        /// </summary>
        public static string materialToUseText {
            get {
                return ResourceManager.GetString("materialToUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string noText {
            get {
                return ResourceManager.GetString("noText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación.
        /// </summary>
        public static string operationText {
            get {
                return ResourceManager.GetString("operationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string originText {
            get {
                return ResourceManager.GetString("originText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida de Almacén.
        /// </summary>
        public static string outputFromWarehouseText {
            get {
                return ResourceManager.GetString("outputFromWarehouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        public static string outputText {
            get {
                return ResourceManager.GetString("outputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada de proceso.
        /// </summary>
        public static string processCheckinText {
            get {
                return ResourceManager.GetString("processCheckinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida de proceso.
        /// </summary>
        public static string processCheckoutText {
            get {
                return ResourceManager.GetString("processCheckoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string processText {
            get {
                return ResourceManager.GetString("processText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad producida.
        /// </summary>
        public static string quantityCreatedText {
            get {
                return ResourceManager.GetString("quantityCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string quantityText {
            get {
                return ResourceManager.GetString("quantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresados.
        /// </summary>
        public static string returnedText {
            get {
                return ResourceManager.GetString("returnedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desechados.
        /// </summary>
        public static string scrappedText {
            get {
                return ResourceManager.GetString("scrappedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección.
        /// </summary>
        public static string selectionText {
            get {
                return ResourceManager.GetString("selectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A usar.
        /// </summary>
        public static string toUseText {
            get {
                return ResourceManager.GetString("toUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string typeOfItemText {
            get {
                return ResourceManager.GetString("typeOfItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string warehouseText {
            get {
                return ResourceManager.GetString("warehouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string yesText {
            get {
                return ResourceManager.GetString("yesText", resourceCulture);
            }
        }
    }
}
