//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procajas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Procajas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string acceptText {
            get {
                return ResourceManager.GetString("acceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelText {
            get {
                return ResourceManager.GetString("cancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string dateText {
            get {
                return ResourceManager.GetString("dateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación destino.
        /// </summary>
        public static string destinyLocationText {
            get {
                return ResourceManager.GetString("destinyLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existentes.
        /// </summary>
        public static string existingText {
            get {
                return ResourceManager.GetString("existingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada.
        /// </summary>
        public static string inputText {
            get {
                return ResourceManager.GetString("inputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada a Almacén.
        /// </summary>
        public static string inputToWarehouseText {
            get {
                return ResourceManager.GetString("inputToWarehouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string invoiceText {
            get {
                return ResourceManager.GetString("invoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string locationText {
            get {
                return ResourceManager.GetString("locationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string materialText {
            get {
                return ResourceManager.GetString("materialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string originText {
            get {
                return ResourceManager.GetString("originText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida de Almacén.
        /// </summary>
        public static string outputFromWarehouseText {
            get {
                return ResourceManager.GetString("outputFromWarehouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        public static string outputText {
            get {
                return ResourceManager.GetString("outputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada de proceso.
        /// </summary>
        public static string processCheckinText {
            get {
                return ResourceManager.GetString("processCheckinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida de proceso.
        /// </summary>
        public static string processCheckoutText {
            get {
                return ResourceManager.GetString("processCheckoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string processText {
            get {
                return ResourceManager.GetString("processText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string quantityText {
            get {
                return ResourceManager.GetString("quantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección.
        /// </summary>
        public static string selectionText {
            get {
                return ResourceManager.GetString("selectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A usar.
        /// </summary>
        public static string toUseText {
            get {
                return ResourceManager.GetString("toUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string warehouseText {
            get {
                return ResourceManager.GetString("warehouseText", resourceCulture);
            }
        }
    }
}
